config/routes.rb
Rails.application.routes.draw do

  root 'events#index', as: 'home_events'	
  devise_for :users

  
  resources :events do
     get  :join, to: 'events#join', as: 'join'
     get  :accept_request, to: 'events#accept_request', as: 'accept_request'
     get  :reject_request, to: 'events#reject_request', as: 'reject_request'
  end

  resources :events 
   get  :my_events, to: 'events#my_events', as: 'my_events'










end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

 include Workflow

 workflow_column :state


 belongs_to :event
 belongs_to :user

 validates :user_id, :uniqueness => {:scope => :event_id}
 
 scope :pending, -> {where(state: 'request_sent')}
 scope :accepted, -> {where(state: 'accepted')}
 scope :rejected, -> {where(state: 'rejected')}

 

 workflow do
  state :request_sent do
   event :accept, :transitions_to => :accepted
   event :reject, :transitions_to => :rejected
  end
   state :accepted
   state :rejected
 end
 
 def self.join_event(user_id, event_id,state)
   self.create(user_id: user_id, event_id: event_id, state: state)
 end
end

app/models/event.rb
class Event < ApplicationRecord
has_many :attendances
has_many :users, :through => :attendances

belongs_to :users, class_name: "User",  optional: true
validates :title, :place, :description, presence: true




  def event_owner(user_id)
    User.find_by id: user_id
  end

  def show_my_events(user_id)
    Event.where(user_id: user_id)
  end


 def created_by_user?(user)
    user_id == user.id
  end


  def pending_requests(event_id)
    Attendance.pending.where(event_id: event_id)
  end
  
  def show_accepted_attendees(event_id)
    Attendance.accepted.where(event_id: event_id)
  end


def self.pending_requests(event_id)
Attendance.where(event_id: event_id, state:
'The request_sent')
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :attendances
has_many :events, class_name: "Event", foreign_key:"user_id", :through => :attendances

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
require "round_robin_tournament"

before_action :authenticate_user!, only: [:new, :index,:edit, :create, :update, :destroy]





   def index
   @events = Event.all
   end


  def new
    @event = Event.new
  end


  def edit
  end



  def show
    @event = Event.find_by(id: params[:id])
     @pending_requests = Attendance.pending.where(event_id: @event.id)
    @attendees = Attendance.accepted.where(event_id: @event.id)
  end



def my_events
    @event = Event.find(current_user.id)
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def join
  @attendance = Attendance.join_event(current_user.id,
  params[:event_id], 'request_sent')
  'Request just sent you' if @attendance.save
  respond_with @attendance
  end

    def accept_request
    @event = Event.find(params[:event_id])
    @attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
    @attendance.accept!
    'Applicant Accepted' if @attendance.save
    respond_with(@attendance)  
    respond_to do |format|
      if @attendance.save
         format.html { redirect_to(@event, :notice => 'Accepted Applicant') }
         format.xml  { head :ok }
       else
        format.html { redirect_to(events_path, :notice => 'Something has gone wrong , please try again.') }
         format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
     end
    
  end
  




  def reject_request
    @event = Event.find(params[:event_id])
    @attendance = Attendance.where(params[:attendance_id]) rescue nil
    @attendance.reject!
    'Applicant Rejected' if @attendance.save
    respond_with(@attendance)
    
     respond_to do |format|
      if @attendance.save
         format.html { redirect_to(@event, :notice => 'Rejected Applicant') }
        format.xml  { head :ok }
      else
        format.html { redirect_to(events_path, :notice => 'Something has gone wrong , please try again.') }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
     end
  end



  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end 

def create
@event = current_user.events.new(event_params)
user_scheduler(current_user.id)
respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
end


private

def event_owner
   if @event.user_id != current_user.id
	redirect_to events_path
	 flash[:notice] = 'You do not have enough permissions to do this'
      end
 end

def set_event
    @event = current_user.events.find_by(id: params[:id])
end


def user_scheduler(user_id)
user = %w(current_user.email)
started = RoundRobinTournament.schedule(user)
end


def event_params
  params.require(:event).permit(:title, :user_id, :start_date, :due_date, :place,:description)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label "Due Date" %><br>
    <%= f.datetime_select :due_date %>
  </div>

  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :description  %><br>
    <%= f.text_area :description %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row">
  <div class="col-lg-8">
    <h3>Last events</h3>  
    <% @events.each do |event| %>
	<h3><%= event.title %></h3>  
        <label>Start Date:</label>&nbsp;&nbsp;&nbsp;&nbsp;
        <%if event.start_date.present?%><%= l event.start_date, :format => :date_format %><%end%> ,        
        <label>Due Date:</label>&nbsp;&nbsp;&nbsp;&nbsp;
        <%if event.due_date.present?%><%= l event.due_date, :format => :date_format %><%end%><br/>
        <label>Place:</label>
        <%= event.place %><br/>
	 <label>Description:</label>
	 <%= event.description %><br/>
	<label>Created:</label><br/>
     <%@event_owner = event.event_owner(event.user_id)%>
        <%= @event_owner.email %>
        <br/>
        <%= link_to 'Show Details', event, :class=>"btn btn-info btn-small" %>
        <% if user_signed_in? && event.user_id == current_user.id %>
    <%= link_to 'Edit', edit_event_path(event), :class=>"btn btn-primary btn-small" %>
    <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-small" %>
        <%end%><br/><br/>
    <% end %>
  
  
<%= link_to 'Create an Event', new_event_path, :class=>"btn btn-default btn-primary" %>    
<br>

app/views/events/my_events.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @event.due_date %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>


<% if user_signed_in? && @event.user_id == current_user.id%>
<label>Join Requests</label>
<% if @pending_requests.present? %>
 <% @pending_requests.each do |p|%>
  <%= p.user.email%>
   <%= link_to 'Accept', event_accept_request_path(:event_id => @event.id, :attendance_id => p.id), :class=>"btn btn-success btn-small" %>
   <%= link_to 'Reject', event_reject_request_path(:event_id => @event.id, :attendance_id => p.id), :class=>"btn btn-danger btn-small" %>
 <%end%>
<%else%>
  <p>No Pending Requests for this event</p>
<%end%>
<%end%>
<br/>


<p>
  <strong>Organizer:</strong>
  <%=current_user.email %>
</p>
 
 <%= link_to 'All Events', events_path, :class=>"btn btn-info btn-small" %>
 <% if user_signed_in? && @event.user_id == current_user.id%>
   <%= link_to 'Edit', edit_event_path(@event), :class=>"btn btn-primary btn-small" %>
   <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-small" %>
  <%end%>

app/views/events/new.html.erb
<h3>Create an Event</h3>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @event.due_date %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>


<% if user_signed_in? && @event.user_id == current_user.id%>
<label>Join Requests</label>
<% if @pending_requests.present? %>
 <% @pending_requests.each do |p|%>
  <%= p.user.email%>
   <%= link_to 'Accept', event_accept_request_path(:event_id => @event.id, :attendance_id => p.id), :class=>"btn btn-success btn-small" %>
   <%= link_to 'Reject', event_reject_request_path(:event_id => @event.id, :attendance_id => p.id), :class=>"btn btn-danger btn-small" %>
 <%end%>
<%else%>
  <p>No Pending Requests for this event</p>
<%end%>
<%end%>
<br/>


<p>
  <strong>Manager:</strong>
  <%=current_user.email %>
</p>
 
 <%= link_to 'All Events', events_path, :class=>"btn btn-info btn-small" %>
 <% if user_signed_in? && @event.user_id == current_user.id%>
   <%= link_to 'Edit', edit_event_path(@event), :class=>"btn btn-primary btn-small" %>
   <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-small" %>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "Time Manager" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

 
    <!-- Size should be 32 x 32 pixels -->
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Time Manager</a>
        </div>

   
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav nav-pills pull-right">
          <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
           <li><%= link_to "#{current_user.email}" %></li>
           <li><%= link_to "My Events", my_events_path %></li>
           <li><%= link_to "New Event", new_event_path %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
           <li><%= link_to "Sign up", new_user_registration_path %></li>
         <% end %>
         </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
<br>
<br>
<br>

    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <%= bootstrap_flash %>
          <%= yield %>
 

      <footer>
        <p>&copy; All rights reserved. Time Manage Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>